export const INITIAL = "https://jsonplaceholder.typicode.com/todos"; //https://api.vtvcab.vn:8889/

// export const HOST = "http://14.248.94.155:4320";
// export const HOST = "http://localhost:4320";
// export const API = HOST + "/api";
// export const API_DULIEU = API + "/duLieu";
// export const API_SHARE = API + "/share";
// export const API_ADMIN_BAN_DO = API + "/admin";
// export const API_BAN_DO = API + "/banDo";
// export const API_STYLE = API + "/style";
// export const API_CONG_CU = API + "/congCu";
// export const API_API = API + "/API";
// export const API_USER = API + "/user";
// export const API_USER_LOGIN = API_USER + "/login";
// export const API_USER_SIGNUP = API_USER + "/signup";
// export const API_USER_GET_INFO = API_USER + "/getUserInfo";
// export const API_QUERY_DU_LIEU = API + "/queryDuLieu";
// export const API_CAU_HINH_DU_LIEU = API + "/cauHinhDuLieu";
// export const API_THEM_MOI_TAI_SAN = API + "/themMoiTaiSan";
export const HOST = "http://localhost:5000";
export const API = HOST + "/api";
export const API_LOGIN = API + "/auth/login"
